site_name: 极光文档
site_author: JPush Offical
site_url: http://docs.jpush.io
site_favicon: favicon.ico
site_description: JPush, JMessage, 极光推送, 极光IM, Android Push, Android 推送, 安卓推送, iOS Push, APNs, Push Notification
copyright: Copyright 2011-2016, jiguang.cn, All Rights Reserved. <br />粤ICP备12056275号-13 深圳市和讯华谷信息技术有限公司
theme_dir: '../themes/readthedocs'

pages:

- 入门指南:
  - '短信验证码概述': 'guideline/JSMS_guide.md'

- Android:
  - 'Android SDK 概述': 'client/Android_SMS_SDK.md'

- iOS:
  - 'iOS SDK 概述': 'client/iOS_SMS_SDK.md'


- REST API:
  - 'REST API 概述': 'server/rest_api_jsms.md'

- 最近更新: 'updates.md'

- 资源下载: 'resources.md'

